import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
	HelpCircle,
	ArrowLeft,
	ChevronDown,
	Flame,
	MessageCircle,
} from "lucide-react";

export const Route = createFileRoute("/faqs")({
	component: FAQsPage,
});

const faqs = [
	{
		question: "What is Lighthouse Dark?",
		answer:
			"Lighthouse Dark is a free web performance and SEO analysis tool that provides detailed insights into your website's speed, accessibility, and search engine optimization. It uses Google PageSpeed Insights API for accurate performance data and AI to generate actionable recommendations.",
	},
	{
		question: "How does the analysis work?",
		answer:
			"When you enter a URL, we fetch your website's content and run it through multiple analysis engines: Google PageSpeed Insights for performance metrics, our SEO analyzer for meta tags and structure, and OpenAI GPT-4 for intelligent recommendations. The entire process typically takes 10-30 seconds.",
	},
	{
		question: "Is Lighthouse Dark free to use?",
		answer:
			"Yes! Lighthouse Dark is completely free to use. There's no sign-up required, no hidden fees, and no premium tiers. We believe web performance analysis should be accessible to everyone.",
	},
	{
		question: "What are Core Web Vitals?",
		answer:
			"Core Web Vitals are a set of metrics that Google uses to measure user experience on your website. They include Largest Contentful Paint (LCP) for loading performance, First Input Delay (FID) / Interaction to Next Paint (INP) for interactivity, and Cumulative Layout Shift (CLS) for visual stability.",
	},
	{
		question: "Why are my mobile and desktop scores different?",
		answer:
			"Mobile and desktop environments have different constraints. Mobile devices typically have slower processors, less memory, and potentially slower network connections. Google simulates these conditions when testing, which often results in lower mobile scores.",
	},
	{
		question: "How accurate are the AI suggestions?",
		answer:
			"Our AI suggestions are generated by analyzing your actual performance data and SEO structure. While they're generally accurate and helpful, they should be considered as guidance rather than absolute rules. Always test changes on your specific website.",
	},
	{
		question: "Can I analyze password-protected or localhost sites?",
		answer:
			"Currently, Lighthouse Dark can only analyze publicly accessible websites. Password-protected pages, localhost URLs, or sites behind firewalls cannot be analyzed. For local development testing, consider using Chrome DevTools Lighthouse.",
	},
	{
		question: "How often should I run an analysis?",
		answer:
			"We recommend running an analysis after any significant changes to your website, such as new deployments, content updates, or infrastructure changes. For ongoing monitoring, weekly or monthly checks are a good practice.",
	},
	{
		question: 'What does "roast" mean?',
		answer:
			"The \"roast\" feature provides honest, sometimes humorous feedback about your website's performance issues. It's designed to make the analysis process more engaging while still delivering valuable insights. Don't worry – we keep it constructive!",
	},
	{
		question: "Is my data private?",
		answer:
			"We don't store any of your analysis results or personal data. Each analysis is performed on-demand and the results are only shown to you. We use the data temporarily to generate AI suggestions but don't retain it afterward.",
	},
];

function FAQItem({ faq, index }: { faq: (typeof faqs)[0]; index: number }) {
	const [isOpen, setIsOpen] = useState(false);

	return (
		<motion.div
			className="glass-surface overflow-hidden rounded-xl transition-all hover:bg-white/5"
			initial={{ opacity: 0, y: 20 }}
			animate={{ opacity: 1, y: 0 }}
			transition={{ delay: 0.1 + index * 0.05 }}
		>
			<button
				type="button"
				className="flex w-full items-center justify-between gap-4 p-5 text-left"
				onClick={() => setIsOpen(!isOpen)}
				aria-expanded={isOpen}
			>
				<span className="text-base font-medium text-light12 dark:text-dark12">
					{faq.question}
				</span>
				<motion.div
					animate={{ rotate: isOpen ? 180 : 0 }}
					transition={{ duration: 0.2 }}
					className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-orange-500/10"
				>
					<ChevronDown className="h-4 w-4 text-orange-400" />
				</motion.div>
			</button>
			<AnimatePresence initial={false}>
				{isOpen && (
					<motion.div
						initial={{ height: 0, opacity: 0 }}
						animate={{ height: "auto", opacity: 1 }}
						exit={{ height: 0, opacity: 0 }}
						transition={{ duration: 0.3, ease: "easeInOut" }}
					>
						<div className="border-t border-white/5 px-5 py-4">
							<p className="text-sm leading-relaxed text-light11 dark:text-dark11">
								{faq.answer}
							</p>
						</div>
					</motion.div>
				)}
			</AnimatePresence>
		</motion.div>
	);
}

function FAQsPage() {
	return (
		<main className="relative min-h-screen pt-24 pb-32">
			<div className="relative z-10 mx-auto max-w-3xl px-6">
				{/* Back Link */}
				<motion.div
					initial={{ opacity: 0, x: -20 }}
					animate={{ opacity: 1, x: 0 }}
					transition={{ duration: 0.4 }}
				>
					<Link
						to="/"
						className="inline-flex items-center gap-2 text-sm text-light11 transition-colors hover:text-orange-400 dark:text-dark11"
					>
						<ArrowLeft className="h-4 w-4" />
						Back to Home
					</Link>
				</motion.div>

				{/* Header */}
				<motion.div
					className="mt-8 mb-12 text-center"
					initial={{ opacity: 0, y: 30 }}
					animate={{ opacity: 1, y: 0 }}
					transition={{ duration: 0.5 }}
				>
					<div className="mb-6 flex justify-center">
						<motion.div
							className="inline-flex"
							initial={{ scale: 0, rotate: -180 }}
							animate={{ scale: 1, rotate: 0 }}
							transition={{ type: "spring", stiffness: 100, delay: 0.1 }}
						>
							<div className="relative">
								<Flame className="h-16 w-16 text-orange-500 drop-shadow-[0_0_30px_rgba(249,115,22,0.4)]" />
								<motion.div
									className="absolute inset-0"
									animate={{ opacity: [0.5, 1, 0.5] }}
									transition={{ duration: 2, repeat: Infinity }}
								>
									<Flame className="h-16 w-16 text-yellow-400/40 blur-sm" />
								</motion.div>
							</div>
						</motion.div>
					</div>

					<motion.div
						className="accent-pill mb-4"
						initial={{ opacity: 0, scale: 0.9 }}
						animate={{ opacity: 1, scale: 1 }}
						transition={{ delay: 0.1 }}
					>
						<HelpCircle className="h-3.5 w-3.5" />
						FAQs
					</motion.div>

					<h1 className="mb-4 text-4xl font-bold tracking-tight text-light12 dark:text-dark12 sm:text-5xl">
						Frequently Asked{" "}
						<span className="bg-linear-to-r from-orange-400 via-red-400 to-pink-400 bg-clip-text text-transparent">
							Questions
						</span>
					</h1>

					<p className="mx-auto max-w-xl text-lg text-light11 dark:text-dark11">
						Got questions? We've got answers. Find everything you need to know
						about Lighthouse Dark.
					</p>
				</motion.div>

				{/* FAQ List */}
				<div className="space-y-3">
					{faqs.map((faq, index) => (
						<FAQItem
							key={`faq-${index}-${faq.question}`}
							faq={faq}
							index={index}
						/>
					))}
				</div>

				{/* Contact CTA */}
				<motion.div
					className="glass-surface mt-12 rounded-2xl p-8 text-center"
					initial={{ opacity: 0, y: 20 }}
					animate={{ opacity: 1, y: 0 }}
					transition={{ delay: 0.8 }}
				>
					<div className="mb-4 inline-flex h-12 w-12 items-center justify-center rounded-full bg-linear-to-br from-orange-500/20 to-red-500/20">
						<MessageCircle className="h-6 w-6 text-orange-400" />
					</div>
					<h3 className="mb-2 text-lg font-semibold text-light12 dark:text-dark12">
						Still have questions?
					</h3>
					<p className="mb-4 text-sm text-light11 dark:text-dark11">
						Can't find what you're looking for? Open an issue on our GitHub.
					</p>
					<a
						href="https://github.com/CodeMeAPixel/LighthouseDark/issues"
						target="_blank"
						rel="noopener noreferrer"
						className="inline-flex items-center gap-2 rounded-full bg-linear-to-r from-orange-500 to-red-500 px-5 py-2.5 text-sm font-semibold text-white shadow-lg shadow-orange-500/25 transition-all hover:scale-105"
					>
						Open an Issue
					</a>
				</motion.div>
			</div>
		</main>
	);
}
